duchamp: parts: Fix 9 errors
1 admin@ip-172-31-29-116:~/crdroid$ cat out/error.log
FAILED: //device/xiaomi/duchamp/parts:XiaomiParts javac (priority: 20)
Outputs: out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar
Error: exited with code: 1
Command: rm -rf "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.tmp" && mkdir -p "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars" && out/host/linux-x86/bin/zipsync -d out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars -l out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars/list -f "*.java"  && (if [ -s out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars/list ] || [ -s out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.rsp ] ; then out/host/linux-x86/bin/soong_javac_wrapper /home/admin/crdroid/rbe/rewrapper --labels=compiler=javac,lang=java,type=compile --platform="Pool=default,container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:1eb7f64b9e17102b970bd7a1af7daaebdb01c3fb777715899ef462d6c6d01a45" --exec_strategy=remote_local_fallback --env_var_allowlist=LANG,LC_MESSAGES,PYTHONDONTWRITEBYTECODE -- prebuilts/jdk/jdk21/linux-x86/bin/
dx.core_core/android_common/aar/androidx.core_core.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/annotation/annotation-jvm/1.9.0-rc01/androidx.annotation_annotation/android_common/local-combined/androidx.annotation_annotation.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib/android_common/local-combined/kotlin-stdlib.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/annotation/annotation-experimental/1.5.0-alpha01/androidx.annotation_annotation-experimental/android_common/aar/androidx.annotation_annotation-experimental.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/collection/collection-jvm/1.5.0-beta01/androidx.collection_collection/android_common/local-combined/androidx.collection_collection.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/concurrent/concurrent-futures/1.3.0-alpha01/androidx.concurrent_concurrent-futures/android_common/local-combined/androidx.concurrent_concurrent-futures.jar:out/soong/.intermediates/prebuilts/tools/common/m2/guava-listenablefuture-prebuilt-jar/android_common/local-combined/guava-listenablefuture-prebuilt-jar.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/core/core-viewtree/1.0.0-alpha01/androidx.core_core-viewtree/android_common/aar/androidx.core_core-viewtree.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/interpolator/interpolator/1.1.0-alpha01/androidx.interpolator_interpolator/android_common/aar/androidx.interpolator_interpolator.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/lifecycle/lifecycle-runtime-android/2.9.0-alpha08/androidx.lifecycle_lifecycle-runtime/android_common/aar/androidx.lifecycle_lifecycle-runtime.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/arch/core/core-common/2.3.0-alpha01/androidx.arch.core_core-common/android_common/local-combined/androidx.arch.core_core-common.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/arch/core/core-runtime/2.3.0-alpha01/androidx.arch.core_core-runtime/android_common/aar/androidx.arch.core_core-runtime.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/lifecycle/lifecycle-common-jvm/2.9.0-alpha08/androidx.lifecycle_lifecycle-common/android_common/local-combined/androidx.lifecycle_lifecycle-common.jar:out/soong/.intermediates/external/jspecify/jspecify/android_common/turbine/jspecify.jar:out/soong/.intermediates/external/kotlinx.coroutines/kotlinx_coroutines-host/linux_glibc_common/local-javac-header/kotli
xternal/kotlinc/kotlin-stdlib-jdk7/android_common/local-combined/kotlin-stdlib-jdk7.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib-jdk8/android_common/local-combined/kotlin-stdlib-jdk8.jar:out/soong/.intermediates/external/kotlinc/kotlin-annotations/android_common/local-combined/kotlin-annotations.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/versionedparcelable/versionedparcelable/1.2.0-rc01/androidx.versionedparcelable_versionedparcelable/android_common/aar/androidx.versionedparcelable_versionedparcelable.jar:out/soong/.intermediates/packages/resources/devicesettings/org.lineageos.settings.resources/android_common/turbine-combined/org.lineageos.settings.resources.jar:out/soong/.intermediates/packages/resources/devicesettings/org.lineageos.settings.resources/android_common/repackaged-jarjar/turbine/org.lineageos.settings.resources.jar:out/soong/.intermediates/hardware/xiaomi/interfaces/xiaomi/hardware/displayfeature_aidl/vendor.xiaomi.hardware.displayfeature_aidl-V2-java/android_common/turbine/vendor.xiaomi.hardware.displayfeature_aidl-V2-java.jar -source 17 -target 17 -d out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes -s out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno @out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.rsp @out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars/list ; fi ) && /home/admin/crdroid/rbe/rewrapper --labels=name=soong_zip,type=tool --platform="Pool=default,container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:1eb7f64b9e17102b970bd7a1af7daaebdb01c3fb777715899ef462d6c6d01a45" --exec_strategy=remote_local_fallback --inputs=out/host/linux-x86/bin/soong_zip,out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno --output_files=out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar.tmp --env_var_allowlist=LANG,LC_MESSAGES,PYTHONDONTWRITEBYTECODE -- out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar.tmp -C out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno -D out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno && /home/admin/crdroid/rbe/rewrapper --labels=name=soong_zip,type=tool --platform="Pool=default,container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:1eb7f64b9e17102b9
Output:
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:47: error: <identifier> expected
context.startServiceAsUser(new Intent(context, ColorModeService.class),
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:47: error: illegal start of type
context.startServiceAsUser(new Intent(context, ColorModeService.class),
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:47: error: <identifier> expected
context.startServiceAsUser(new Intent(context, ColorModeService.class),
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:51: error: <identifier> expected
context.startServiceAsUser(new Intent(context, TouchSamplingService.class), UserHandle.CURRENT);
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:51: error: illegal start of type
context.startServiceAsUser(new Intent(context, TouchSamplingService.class), UserHandle.CURRENT);
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:51: error: <identifier> expected
context.startServiceAsUser(new Intent(context, TouchSamplingService.class), UserHandle.CURRENT);
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:55: error: <identifier> expected
context.startService(turboChargingIntent);
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:55: error: <identifier> expected
context.startService(turboChargingIntent);
^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/BootCompletedReceiver.java:72: error: reached end of file while parsing
}
^
9 errors

Signed-off-by: zenin1504 <kayozzprojects@yandex.com>

duchamp: parts: Fix more errors

1 admin@ip-172-31-29-116:~/crdroid$ cat out/error.log              FAILED: //device/xiaomi/duchamp/parts:XiaomiParts javac            Outputs: out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar                                                            Error: exited with code: 1                                                                                                            =compile --platform="Pool=default,container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:1eb7f64b9e17102b970bd7a1af7daaebdb01c3fb777715899ef462d6c6d01a45" --exec_strategy=remote_local_fallback --env_var_allowlist=LANG,LC_MESSAGES,PYTHONDONTWRITEBYTECODE -- prebuilts/jdk/jdk21/linux-x86/bin/javac -J-Xmx4096M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -proc:none -g:source,lines -Xlint:-dep-ann --system=out/soong/.intermediates/build/soong/java/core-libraries/stable-core-platform-api-stubs-system-modules/android_common/system -classpath out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/busybox/R.jar:out/soong/.intermediates/external/libphonenumber/libphonenumber-platform/android_common/turbine/libphonenumber-platform.jar:out/soong/.intermediates/external/tagsoup/tagsoup/android_common/turbine/tagsoup.jar:out/soong/.intermediates/external/rappor/rappor/android_common/turbine/rappor.jar:out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:out/soong/.intermediates/frameworks/base/framework/android_common/repackaged-jarjar/turbine/framework.jar:out/soong/.intermediates/frameworks/base/packages/SettingsLib/SettingsLib/android_common/turbine-combined/SettingsLib.jar:out/soong/.intermediates/frameworks/base/packages/SettingsLib/SettingsLib/android_common/repackaged-jarjar/turbine/SettingsLib.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/core/core/1.16.0-alpha01/androidx.core_core/android_common/aar/androidx.core_core.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/annotation/annotation-jvm/1.9.0-rc01/androidx.annotation_annotation/android_common/local-combined/androidx.annotation_annotation.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib/android_common/local-combined/kotlin-stdlib.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/annotation/annotation-experimental/1.5.0-alpha01/androidx.annotation_annotation-experimental/android_common/aar/androidx.annotation_annotation-experimental.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/collection/collection-jvm/1.5.0-beta01/androidx.collection_collection/android_common/local-combined/androidx.collection_collection.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/concurrent/concurrent-futures/1.3.0-alpha01/and                                                           le-common-jvm/2.9.0-alpha08/androidx.lifecycle_lifecycle-common/android_common/local-combined/androidx.lifecycle_lifecycle-common.jar:out/soong/.intermediates/external/jspecify/jspecify/android_common/turbine/jspecify.jar:out/soong/.intermediates/external/kotlinx.coroutines/kotlinx_coroutines-host/linux_glibc_common/local-javac-header/kotlinx_coroutines-host.jar:out/soong/.intermediates/external/kotlinx.atomicfu/kotlinx_atomicfu/linux_glibc_common/local-javac-header/kotlinx_atomicfu.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib/linux_glibc_common/local-combined/kotlin-stdlib.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib-jdk7/linux_glibc_common/local-combined/kotlin-stdlib-jdk7.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib-jdk8/linux_glibc_common/local-combined/kotlin-stdlib-jdk8.jar:out/soong/.intermediates/external/kotlinc/kotlin-annotations/linux_glibc_common/local-combined/kotlin-annotations.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/profileinstaller/profileinstaller/1.4.0-alpha02/androidx.profileinstaller_profileinstaller/android_common/aar/androidx.profileinstaller_profileinstaller.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/startup/startup-runtime/1.2.0-alpha02/androidx.startup_startup-runtime/android_common/aar/androidx.startup_startup-runtime.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/tracing/tracing/1.3.0-alpha02/androidx.tracing_tracing/android_common/aar/androidx.tracing_tracing.jar:out/soong/.intermediates/external/kotlinx.coroutines/kotlinx_coroutines_android/android_common/kotlin_headers/kotlinx_coroutines_android.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib-jdk7/android_common/local-combined/kotlin-stdlib-jdk7.jar:out/soong/.intermediates/external/kotlinc/kotlin-stdlib-jdk8/android_common/local-combined/kotlin-stdlib-jdk8.jar:out/soong/.intermediates/external/kotlinc/kotlin-annotations/android_common/local-combined/kotlin-annotations.jar:out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/versionedparcelable/versionedparcelable/1.2.0-rc01/androidx.versionedparcelable_versionedparcelable/android_common/aar/androidx.versionedparcelable_versionedparcelable.jar:out/soong/.intermediates/packages/resources/devicesettings/org.lineageos.settings.resources/android_common/turbine-combined/org.lineageos.settings.resources.jar:out/soong/.intermediates/packages/resources/devicesettings/org.lineageos.settings.resources/android_common/repackaged-jarjar/turbine/org.lineageos.settings.resources.jar:out/soong/.intermediates/hardware/xiaomi/interfaces/xiaom
ype=tool --platform="Pool=default,container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:1eb7f64b9e17102b970bd7a1af7daaebdb01c3fb777715899ef462d6c6d01a45" --exec_strategy=remote_local_fallback --inputs=out/host/linux-x86/bin/soong_zip,out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes --output_files=out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.tmp --env_var_allowlist=LANG,LC_MESSAGES,PYTHONDONTWRITEBYTECODE -- out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.tmp -C out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes -D out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes && if ! cmp -s "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.tmp" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar"; then mv "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar.tmp" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/XiaomiParts.jar"; fi && if ! cmp -s "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar"; then mv "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar.tmp" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/anno.srcjar"; fi && rm -rf "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/srcjars" "out/soong/.intermediates/device/xiaomi/duchamp/parts/XiaomiParts/android_common/javac/classes"
Output:                                                            device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingService.java:28: error: package com.xiaomi.settings.utils does not exist                                                  import com.xiaomi.settings.utils.FileUtils;                                                        ^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingSettingsFragment.java:34: error: package com.xiaomi.settings.utils does not exist
import com.xiaomi.settings.utils.FileUtils;
^                                  device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingUtils.java:27: error: package org.lineageos.settings.utils does not exist                                                 import org.lineageos.settings.utils.FileUtils;                                                        ^
device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingService.java:133: error: cannot find symbol                    String currentState = FileUtils.readOneLine(TouchSamplingUtils.HTSR_FILE);                                                                                  ^                                      symbol:   variable FileUtils
location: class TouchSamplingService                             device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingService.java:136: error: cannot find symbol
FileUtils.writeLine(TouchSamplingUtils.HTSR_FILE, Integer.toString(state));                                                           ^
symbol:   variable FileUtils                                       location: class TouchSamplingService                             device/xiaomi/duchamp/parts/src/com/xiaomi/settings/touchsampling/TouchSamplingUtils.java:41: error: cannot find symbol                       FileUtils.writeLine(HTSR_FILE, Integer.toString(htsrState));
^
symbol:   variable FileUtils                                       location: class TouchSamplingUtils                               6 errors

Signed-off-by: zenin1504 <kayozzprojects@yandex.com>

Revert "duchamp: rootdir: Disable rotation suggestion by default"

This reverts commit e8ec442b17da88707a2916ce03cb1145458b17bd.